<Project>
  <PropertyGroup>
    <!--Set this to your project's name-->
    <ProjectName>LeftyExpie</ProjectName>
    <!--Set this to the game's main folder-->
    <BaseGamePath>C:\Program Files (x86)\Steam\steamapps\common\Casualties Unknown Demo</BaseGamePath>
    <BepInExDir>$(BaseGamePath)/BepInEx</BepInExDir>
    <GameAssembliesDir>$(BaseGamePath)/CasualtiesUnknown_Data/Managed</GameAssembliesDir>
  </PropertyGroup>
</Project>
